import { defineConfig } from "oxlint";

export default defineConfig({
  options: {},
  categories: {
    correctness: "warn",
    nursery: "warn",
    pedantic: "warn",
    perf: "error",
    restriction: "error",
    style: "warn",
    suspicious: "error",
  },
  env: {
    browser: true,
    es2022: true,
    node: true,
  },
  overrides: [
    {
      files: ["**/*.test.ts", "**/*.test.tsx"],
      rules: {
        "init-declarations": "off",
      },
    },
    {
      files: ["*.config.ts"],
      rules: {
        "import/no-nodejs-modules": "off",
      },
    },
  ],
  plugins: ["react", "react-perf", "typescript", "eslint", "import", "vitest"],
  rules: {
    complexity: "off",
    "eslint/no-unused-vars": [
      "error",
      {
        argsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
      },
    ],
    "eslint/curly": ["error", "multi-line"],
    "func-style": ["error", "declaration"],
    "id-length": ["warn", { exceptions: ["T", "z"] }],
    "jsx-max-depth": "off",
    "jsx-no-jsx-as-prop": "off",
    "jsx-no-new-array-as-prop": "off",
    "jsx-no-new-function-as-prop": "off",
    "jsx-no-new-object-as-prop": "off",
    "max-lines": "off",
    "max-lines-per-function": "off",
    "max-statements": "off",
    "no-magic-numbers": "off",
    "no-nested-ternary": "error",
    "no-ternary": "off",
    "no-undefined": "off",
    "no-use-before-define": "off",
    "no-void": "off",
    "no-warning-comments": "off",
    "react/jsx-filename-extension": ["warn", { extensions: [".jsx", ".tsx"] }],
    "react/jsx-props-no-spreading": "off",
    "react/no-multi-comp": "off",
    "react/only-export-components": "off",
    "react/react-in-jsx-scope": "off",
    "sort-imports": "off",
    "sort-keys": "off",
    "typescript/no-explicit-any": "error",
    "typescript/explicit-function-return-type": "off",
    "typescript/explicit-module-boundary-types": "off",
    "import/exports-last": "off",
    "import/no-named-export": "off",
    "import/no-default-export": "off",
    "import/group-exports": "off",
    "import/prefer-default-export": "off",
    "import/no-named-as-default": "off",
    "import/max-dependencies": "off",
    "import/no-relative-parent-imports": "off",
    "eslint/no-duplicate-imports": ["off", { allowSeparateTypeImports: true }],
    "vitest/prefer-describe-function-title": "off",
    "vitest/prefer-import-in-mock": "off",
    "vitest/no-importing-vitest-globals": "off",
    "vitest/prefer-importing-vitest-globals": "off",
    "vitest/prefer-strict-boolean-matchers": "off",
    "vitest/require-mock-type-parameters": "off",
    "vitest/require-test-timeout": "off",
    "vitest/require-top-level-describe": "off",
    "vitest/no-hooks": "off",
    // Page sub-components need to import Route modules
    "import/no-cycle": "off",
  },
});
