import {
  RECOMMENDED_RULES,
  TANSTACK_START_RULES,
} from "oxlint-plugin-react-doctor";
import { defineConfig } from "oxlint";

export default defineConfig({
  jsPlugins: [
    {
      name: "react-doctor",
      specifier: "oxlint-plugin-react-doctor",
    },
  ],
  options: {},
  categories: {
    correctness: "error",
    perf: "error",
    restriction: "error",
    style: "warn",
    suspicious: "error",
  },
  env: {
    browser: true,
    es2022: true,
    node: true,
  },
  overrides: [
    {
      files: ["**/*.test.ts", "**/*.test.tsx"],
      plugins: ["vitest", "jest"],
      rules: {
        "init-declarations": "off",
        "jest/no-untyped-mock-factory": "off",
        "vitest/prefer-describe-function-title": "off",
        "vitest/prefer-import-in-mock": "off",
        "vitest/no-importing-vitest-globals": "off",
        "vitest/prefer-importing-vitest-globals": "warn",
        "vitest/prefer-strict-boolean-matchers": "warn",
        "vitest/require-mock-type-parameters": "warn",
        "vitest/require-test-timeout": "off",
        "vitest/require-top-level-describe": "warn",
        "vitest/no-hooks": "off",
        "vitest/no-test-return-statement": "warn",
        "vitest/no-conditional-in-test": "off",
        "vitest/prefer-expect-assertions": "off",
        "vitest/no-conditional-expect": "off",
        "jest/prefer-ending-with-an-expect": "off",
        "jest/no-conditional-expect": "off",
        "jest/no-hooks": "off",
        "jest/require-top-level-describe": "warn",
        "jest/prefer-expect-assertions": "off",
        "jest/no-conditional-in-test": "off",
      },
    },
    {
      files: ["src/test/e2e/*.test.ts"],
      plugins: ["vitest"],
      rules: {
        "vitest/prefer-importing-vitest-globals": "off",
      },
    },
    {
      files: ["*.config.ts"],
      rules: {
        "import/no-nodejs-modules": "off",
      },
    },
    {
      files: ["src/test/*.ts"],
      rules: {
        "import/no-nodejs-modules": "off",
      },
    },
    {
      files: ["scripts/**/*.ts"],
      globals: {
        // oxlint-disable-next-line id-length
        $: "readonly",
        question: "readonly",
      },
      rules: {
        complexity: "off",
        "no-console": "off",
        "import/unambiguous": "off",
        "import/no-nodejs-modules": "off",
      },
    },
  ],
  plugins: ["react", "react-perf", "typescript", "eslint", "import"],
  rules: {
    ...RECOMMENDED_RULES,
    ...TANSTACK_START_RULES,
    "react-doctor/react-compiler-no-manual-memoization": "off",
    "react-doctor/no-multi-component-file": "off",
    "react-doctor/anchor-target-exists": "off",
    "react-doctor/only-export-components": "off",
    "react-doctor/jsx-no-jsx-as-prop": "off",
    "react-doctor/jsx-max-depth": "off",
    "react-doctor/jsx-no-new-array-as-prop": "off",
    "react-doctor/jsx-no-new-object-as-prop": "off",
    "react-perf/jsx-no-new-function-as-prop": "off",
    complexity: ["error", { max: 10 }],
    "eslint/no-unused-vars": [
      "error",
      {
        argsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
      },
    ],
    "eslint/curly": ["error", "multi-line"],
    "func-style": ["error", "declaration"],
    "id-length": ["warn", { exceptions: ["T", "z"] }],
    "jsx-max-depth": "off",
    "jsx-no-jsx-as-prop": "off",
    "jsx-no-new-array-as-prop": "off",
    "react-doctor/jsx-no-new-function-as-prop": "off",
    "jsx-no-new-object-as-prop": "off",
    "max-lines": "off",
    "max-lines-per-function": "off",
    "max-statements": "off",
    "no-magic-numbers": "off",
    "one-var": ["error", "never"],
    "no-nested-ternary": "error",
    "no-ternary": "off",
    "no-undefined": "off",
    "no-use-before-define": "off",
    "no-void": "off",
    "no-warning-comments": "off",
    "react/jsx-filename-extension": ["warn", { extensions: [".jsx", ".tsx"] }],
    "react/jsx-props-no-spreading": "off",
    "react/no-multi-comp": "off",
    "react/only-export-components": "off",
    "react/react-in-jsx-scope": "off",
    "react/forbid-component-props": "off",
    "react/jsx-no-literals": "off",
    "sort-imports": "off",
    "sort-keys": "off",
    "typescript/no-explicit-any": "error",
    "typescript/explicit-function-return-type": "off",
    "typescript/explicit-module-boundary-types": "off",
    "import/exports-last": "off",
    "import/no-named-export": "off",
    "import/no-default-export": "off",
    "import/group-exports": "off",
    "import/prefer-default-export": "off",
    "import/no-named-as-default": "off",
    "import/max-dependencies": "off",
    "import/no-relative-parent-imports": "off",
    "eslint/no-duplicate-imports": ["off", { allowSeparateTypeImports: true }],
    "import/no-cycle": "off",
  },
});
