autoInstallPeers: false
minimumReleaseAge: 2880
resolutionMode: highest
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
allowBuilds:
  '@parcel/watcher': true
  core-js-pure: true
  esbuild: true
  msw: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js-pure
  - esbuild
  - msw
