name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_DB: react-router-starter-test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v5

      - uses: marocchino/tool-versions-action@v1
        id: versions

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.versions.outputs.nodejs }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: ${{ steps.versions.outputs.pnpm }}
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-10052025
          restore-keys: |
            ${{ runner.os }}-pnpm-store-10052025

      - name: Cache playwright deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-build-playwright-10052025
          restore-keys: |
            ${{ runner.os }}-build-playwright-10052025

      - name: Install dependencies
        run: |
          pnpm i
          npx playwright install

      - name: Lint
        run: |
          bin/lint
          bin/ts-check

      - name: Vitest
        run: |
          pnpm prisma db push
          bin/test-vitest
        env:
          SECRET_KEY_BASE: ChangeThisBeforeShippingToProdOrYouWillBeFired
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/react-router-starter-test

      - name: E2E
        run: |
          bin/test-e2e
        env:
          SECRET_KEY_BASE: ChangeThisBeforeShippingToProdOrYouWillBeFired
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/react-router-starter-test
          NODE_ENV: production
